Bootstrap:docker
From:alpine

%files 
	kafka_consumer.py
	cassandra_connect.py
	cassandra_query_system.py
	avro-python3-1.8.2.tar.gz 
	emb_schema.avsc 
%post 
	apk add --no-cache python3 	
	python3 -m ensurepip && \
    	rm -r /usr/lib/python*/ensurepip && \
	pip3 install --upgrade pip setuptools && \
	if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
	if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi && \
	rm -r /root/.cache
	
	pip3 install kafka-python
	pip3 install cassandra-driver
	# unpack avro
	tar xvf avro-python3-1.8.2.tar.gz
	cd avro-python3-1.8.2
	python3 setup.py install

%runscript
	cd /
	# set up database
	python3 cassandra_connect.py
	python3 kafka_consumer.py
	
